<?php
/**
 * User: GabrielCHEN
 * Date: 2019/3/20
 * Time: 14:05
 */

namespace App\HttpController\Api;

use EasySwoole\Http\AbstractInterface\Controller;
use EasySwoole\Http\Message\Status;

abstract class AbstractBase extends Controller
{
    function index()
    {
        $this->actionNotFound('index');
    }

    protected function actionNotFound(?string $action)
    {
        parent::actionNotFound($action); // TODO: Change the autogenerated stub
        $this->writeJson(Status::CODE_NOT_FOUND);
    }
}
